package rules;
dialect  "java"
import com.test.facts.TemperatureAlert
import com.test.facts.AccelerometerAlert
import com.test.facts.SensorReading
import com.test.utilities.Helper

declare TemperatureAlert
    @role(event)
    @timestamp (eventDestinationTimestamp)
    @expires(20s)
end

declare AccelerometerAlert
    @role(event)
    @timestamp (eventDestinationTimestamp)
    @expires(20s)
end

/**
This rule prints out if holder is running out of money
**/
rule "readingTemparature"
    when
        $reading : SensorReading(getType() == "TemperatureSensorReading" && getOneValue() < 21 )
    then
        System.out.println("Reading found with values: " + $reading.getOneValue());
        Helper.help(drools, "Test Helper");
        TemperatureAlert alert = new TemperatureAlert("Temperature alert: " + $reading.getId(), $reading);
        insert(alert);
end

rule "Alert Scan Event Processing of Temperature"
    when
        $e1: TemperatureAlert()
    then
        $e1.execute();
        retract($e1)
end

rule "Alert Scan Event Processing of Accelerometer"
    when
        $e2: AccelerometerAlert()
    then
        System.out.println("Accelerometer Alert from rule");
end