package rules;
dialect  "java"
import com.test.facts.Alert
import com.test.facts.SensorReading
import com.test.utilities.Helper

/**
This rule prints out if holder is running out of money
**/
rule "readingCommon"
    when
        $reading : SensorReading( $values: values )
    then

        System.out.println("Reading found with values: " + $values);
        Helper.help(drools, "Test Helper");
end
